### ISSUE TITLE
[BUG] No config with wider screen and home is not clickable 

### ISSUE THREAD

**Issue by ptrkp** [flixlix/flixlix-cards#176]
Hi,

If I wider the layout over more than one column the config options disappears. Changing to the standard layout the config options returns. Not sure if this is a BUG but the Home icon is not clickable.
![image](https://github.com/user-attachments/assets/d7cc23fd-3a0c-4c24-a85e-608a79ddc164)
![image](https://github.com/user-attachments/assets/ecf9a27e-badd-4a26-99f4-3e84d3ddcb6c)

**Comment by lorenzofattori** [comment]
here no matter how I configure the layout the config windows is always empty now, I can only edit from code etitor

![image](https://github.com/user-attachments/assets/8d5a8222-9798-42f2-8ee2-8d2c3ee8c94b)

**Comment by ehendrix23** [comment]
Same issue here. :-) 
If I remove the following from the configuration then it works:
`layout_options:
  grid_columns: full`

Following error is show in the console:
`Uncaught (in promise) Tt: At path: layout_options -- Expected a value of type `never`, but received: `[object Object]`
    at Rt (http://192.168.1.10:8123/hacsfiles/power-flow-card-plus/power-flow-card-plus.js?hacstag=618081815024:1:108058)
    at Ht (http://192.168.1.10:8123/hacsfiles/power-flow-card-plus/power-flow-card-plus.js?hacstag=618081815024:1:107896)
    at Pa.setConfig (http://192.168.1.10:8123/hacsfiles/power-flow-card-plus/power-flow-card-plus.js?hacstag=618081815024:1:193414)
    at Pa.value (http://192.168.1.10:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:60079)
    at Pa.i [as setConfig] (http://192.168.1.10:8123/hacsfiles/lovelace-card-mod/card-mod.js:1:53173)
    at i.value (http://192.168.1.10:8123/frontend_latest/22992.YNszCLnOOls.js:5:29781)`

**Comment by HABrain** [comment]
Hi, 
in wich file I have to remove this line ?
In the file /homeassistant/custom_components/hacs/config_flow.py I can´t find this line...
Thx :-)
